/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS `stocks` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `stocks`;

CREATE TABLE IF NOT EXISTS `purchased` (
  `ID` int(4) NOT NULL AUTO_INCREMENT,
  `Ticker` varchar(6) NOT NULL,
  `QTY` int(4) NOT NULL,
  `Price` decimal(6,2) NOT NULL,
  `Class` varchar(10) NOT NULL,
  `Purchase_Date` date NOT NULL,
  `Market` varchar(10) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `sales` (
  `ID` int(4) NOT NULL AUTO_INCREMENT,
  `Ticker` varchar(6) NOT NULL,
  `QTY` int(4) NOT NULL,
  `Price` decimal(6,2) NOT NULL,
  `Sale_Date` date NOT NULL,
  `Market` varchar(10) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
